### ISSUE TITLE
GETS STUCK WHEN SENDING IS INITIATED

### ISSUE THREAD

**Issue by Crewxx** [nubonics/Bulk-Email-Sender#1]
1.) NOT SHOWING IF SENDING IS SUCCESSFUL OR NOT, JUST GET STUCK. 

2.) HOW DO YOU CUSTOMIZED THE MESSAGE THAT NEEDS TO BE SENT?

THANKS

**Comment by nubonics** [comment]
Feel free to contact me on discord and I will help you resolve the issue there.
Discord: nubonix#3648

**Comment by Crewxx** [comment]
OK, great
